server:
  port: 8761

eureka:
  instance:
    hostname: 10.107.47.192
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

oauth2:
  client:
    tokenUri: http://localhost:8080/uaa/oauth/token
    authorizationUri: http://localhost:8080/uaa/oauth/authorize
    clientId: acme
    clientSecret: acmesecret
  resource:
    jwt:
      keyValue: http://localhost:8080/uaa/oauth/token_key
      id: openid
      serviceId: ${PREFIX:}resource